---
version: '3'
services:
  backtesting:
    image: freqtradeorg/freqtrade:develop
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      backtesting
      --strategy ${STRATEGY}
      --timerange ${TIMERANGE}
      --config user_data/config.json
      --datadir user_data/freqtrade-test-data/user_data/data/binance
      --max-open-trades ${MAX_OPEN_TRADES}
      --stake-amount ${STAKE_AMOUNT}
  plot-profit:
    image: freqtradeorg/freqtrade:develop_plot
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      plot-profit
      --timerange ${TIMERANGE}
      --datadir user_data/freqtrade-test-data/user_data/data/binance
      --config user_data/config.json
      --export-filename ${STRATEGY}-${TIMERANGE}.html
      --strategy ${STRATEGY}
  plot-dataframe:
    image: freqtradeorg/freqtrade:develop_plot
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      plot-profit
      --timerange ${TIMERANGE}
      --datadir user_data/freqtrade-test-data/user_data/data/binance
      --config user_data/config.json
      --export-filename ${STRATEGY}-${TIMERANGE}.html
      --strategy ${STRATEGY}
