name: Backtest

on: [push, pull_request]

jobs:
  main_job:
    strategy:
      fail-fast: false
      matrix:
        timerange: [20210101-20210201, 20210201-20210301, 20210301-20210401, 20210401-20210501, 20210601-20210701]
        opentrades: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

# January
      - name: Run Backtest ${{ matrix.opentrades }} trades ${{ matrix.timerange }}
        env:
          MAX_OPEN_TRADES: ${{ matrix.opentrades }}
          STAKE_AMOUNT: unlimited
          TIMERANGE: ${{ matrix.timerange }}
        run: docker-compose run --rm backtesting > backtest/backtest_${{ matrix.timerange }}_${{ matrix.opentrades }}.txt

      - name: Show Backtest ${{ matrix.timerange }} ${{ matrix.opentrades }}
        run: cat backtest/backtest_${{ matrix.timerange }}_${{ matrix.opentrades }}.txt

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: backtest
          path: backtest/