name: Backtest

on: [push, pull_request]

jobs:
  main_job:
    strategy:
      fail-fast: false
      matrix:
        #timerange: [20210101-20210201, 20210201-20210301, 20210301-20210401, 20210401-20210501, 20210601-20210701]
        timerange: [20210601-20210701]
        opentrades: [1]
        strategy: [NostalgiaForInfinityNext, HarmonicDivergence]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run Backtest ${{ matrix.opentrades }} trades ${{ matrix.timerange }}
        env:
          MAX_OPEN_TRADES: ${{ matrix.opentrades }}
          STAKE_AMOUNT: unlimited
          TIMERANGE: ${{ matrix.timerange }}
          STRATEGY: ${{ matrix.strategy}}
        run: docker-compose run --rm backtesting > backtest_${{ matrix.timerange }}_${{ matrix.opentrades }}_${{matrix.strategy}}.txt

      - name: Plot Profit ${{ matrix.opentrades }} trades ${{ matrix.timerange }} HarmonicDivergence
        env:
          MAX_OPEN_TRADES: ${{ matrix.opentrades }}
          STAKE_AMOUNT: unlimited
          TIMERANGE: ${{ matrix.timerange }}
          STRATEGY: ${{ matrix.strategy}}
        run: docker-compose run --rm plot-profit
        
      - name: Plot Trades ${{ matrix.opentrades }} trades ${{ matrix.timerange }} HarmonicDivergence
        env:
          MAX_OPEN_TRADES: ${{ matrix.opentrades }}
          STAKE_AMOUNT: unlimited
          TIMERANGE: ${{ matrix.timerange }}
          STRATEGY: ${{ matrix.strategy}}
        run: docker-compose run --rm plot-dataframe

      - name: Show Backtest ${{ matrix.timerange }} ${{ matrix.opentrades }}
        run: cat backtest_${{ matrix.timerange }}_${{ matrix.opentrades }}_${{matrix.strategy}}.txt

      - name: 'Upload Artifact Backtest Log'
        uses: actions/upload-artifact@v2
        with:
          name: backtest_${{ matrix.strategy}}_result
          path: backtest_${{ matrix.timerange }}_${{ matrix.opentrades }}_${{matrix.strategy}}.txt

      - name: 'Upload Artifact Profit Plot'
        uses: actions/upload-artifact@v2
        with:
          name: backtest_${{ matrix.strategy}}_result
          path: user_data/plot