name: Backtest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"

      - name: Run Backtest
        run: docker-compose run --rm backtesting > backtest.txt
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: backtest
          path: backtest.txt
          retention-days: 5