name: Backtest

on: [push, pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"

      - name: Backtest 1 unlimited
        env:
          MAX_OPEN_TRADES: 4
          STAKE_AMOUNT: unlimited
        run: docker-compose run --rm backtesting > backtest.txt && cat backtest.txt

      - name: Backtest 2 unlimited
        env:
          MAX_OPEN_TRADES: 4
          STAKE_AMOUNT: unlimited
        run: docker-compose run --rm backtesting > backtest.txt && cat backtest.txt

      - name: Backtest 3 unlimited
        env:
          MAX_OPEN_TRADES: 4
          STAKE_AMOUNT: unlimited
        run: docker-compose run --rm backtesting > backtest.txt && cat backtest.txt

      - name: Backtest 4 unlimited
        env:
          MAX_OPEN_TRADES: 4
          STAKE_AMOUNT: unlimited
        run: docker-compose run --rm backtesting > backtest.txt && cat backtest.txt

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: backtest.txt